### ISSUE TITLE
Where to draw the line?

### ISSUE THREAD

**Issue by hfossli** [Swift-Flow/CounterExample#1]
Hey,

I don't know where else to post this question. I hope this github issue is okay.
I am new to redux and have been reading a lot about it lately. 

According to this video https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree going redux means that you are storing the whole app state as a single immutable object. Obviously somewhere a line has to be drawn. 

Where do you draw the line and how do you decide it is the right place? For instance I see you are switching tabs redux style. Returning false and letting the reducers change state. 

```
extension AppDelegate: UITabBarControllerDelegate {

    func tabBarController(tabBarController: UITabBarController,
        shouldSelectViewController viewController: UIViewController) -> Bool {

        if viewController is CounterViewController {
            mainStore.dispatch(
                SetRouteAction(["TabBarViewController", CounterViewController.identifier])
            )
        } else if viewController is StatsViewController {
            mainStore.dispatch(
                SetRouteAction(["TabBarViewController", StatsViewController.identifier])
            )
        }

        return false
    }

}
```

There's a lot of state going on in a normal application. Like scroll offset in a scrollview, user typing individual characters as input in a text field or subtle animations when tapping a button. I mean the blinking caret in the text field can't and shouldn't be handled by redux. :D What are your thoughts on this?

**Comment by hfossli** [comment]
Haha, weirdest github issue ever.

**Comment by Ben-G** [comment]
@hfossli Fantastic questions! Sorry I missed this issue - for some reason my notification settings are incorrect for this project.

It's a good question - for now I'm leaving pure view state out of the store; this includes the scroll position and the blinking caret. I only store view related information that is _semantically_ relevant.

This is e.g. why I intercept the tab bar button tap; it changes the current scene within the app - this is state that I definitely want to capture and restore.

If the scroll position is incredibly relevant to the UX of your specific app - then it probably should be stored within the application state as well!

My current mental framework for _drawing the line_ is: when a user quits the app and reopens it, and I want to recreate the scene they are currently in, with the state they left it at - what is the information I need to accomplish that?

E.g. having the blinking caret be in a different state then in which the user saw it before quitting the app, would not be an issue.

Being on an entirely different View Controller would be.

I hope this helps! And I'm sure we as a community will find more robust guidelines over time :smile: 

P.S.: The repo is definitely the right place to ask such questions!

**Comment by hfossli** [comment]
Allright! This definetely answers a lot of my questions. Thank you!
