### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by MojtabaHs** [Swift-Flow/CounterExample#12]
Since ReSwift 4.X released long time ago, perhaps this example should update as well. Because this is the main and primary example source of 3 included frameworks.

One of the most confusing changes for me is `stateTransform: <#T##(Subscription<_>) -> Subscription<NavigationState>#>)
` in Router initializer from "ReSwift-Router" and I didn't find a clear documentation or example about it.

So it would be grate if you guys plan to update this repo ( starting from the issue above ;) )

thanks

**Comment by yamoridon** [comment]
I made a PR for this!
#13 Run with Swift 4.2

**Comment by DivineDominion** [comment]
Closing this thanks to #13 👍
