### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by zh-wowtv** [Swift-Flow/CounterExample#4]
My steps:

> git clone https://github.com/ReSwift/CounterExample-Navigation-TimeTravel.git
> cd CounterExample-Navigation-TimeTravel
> carthage update

Got the following error message:

> **\* Building scheme "ReSwiftRecorder" in ReSwiftRecorder.xcodeproj
> *\* BUILD FAILED **
> 
> The following build commands failed:
>   CompileSwift normal arm64 /Users/zhouhao/Projects/Swift/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/RecordingStore.swift
>   CompileSwift normal arm64 /Users/zhouhao/Projects/Swift/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistorySliderView.swift
>   CompileSwift normal arm64 /Users/zhouhao/Projects/Swift/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistoryCollectionViewCell.swift
>   CompileSwift normal arm64 /Users/zhouhao/Projects/Swift/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistoryView.swift
>   CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> (5 failures)

**Comment by Ben-G** [comment]
Hey @zh-wowtv,

would you mind trying the following carthage install command?

```
carthage update --no-use-binaries --platform ios
```

**Comment by goldenbearkin** [comment]
The following build commands failed:
    CompileSwift normal arm64 /development/github/ios/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/RecordingStore.swift
    CompileSwift normal arm64 /development/github/ios/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistorySliderView.swift
    CompileSwift normal arm64 /development/github/ios/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistoryCollectionViewCell.swift
    CompileSwift normal arm64 /development/github/ios/CounterExample-Navigation-TimeTravel/Carthage/Checkouts/ReSwift-Recorder/ReSwiftRecorder/UI/StateHistoryView.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

I have tried 'carthage update --no-use-binaries --platform ios'. Still unable to kick-off.

**Comment by Ben-G** [comment]
@goldenbearkin @zh-wowtv 

Really sorry for the slow follow up on this! I just tested this on my end and I know remember how I set up this project. Instead of including the carthage build product I'm only using carthage for fetching the projects.

This means the `checkout` command is sufficient to get this project to compile:

```
carthage checkout
```

I'll make sure to add this to the documentation.

Sorry for the issues, and please let me know if this command worked for you!

**Comment by Ben-G** [comment]
@zh-wowtv @goldenbearkin to be more specific, the full command should be

```
carthage update --no-build && carthage checkout
```

Could you let me know if this works for you?

**Comment by bhanuprakash0024** [comment]
@Ben-G  I got the same issue by doing just
`carthage update`
now after using 
`carthage update --no-build && carthage checkout`
everything worked fine :)
I guess you can  close this issue now @zh-wowtv
