### ISSUE TITLE
Where to view the demo of the app

### ISSUE THREAD

**Issue by bhanuprakash0024** [Swift-Flow/CounterExample#6]
My Xcode's Version 7.3.1 (7D1014)
Simulator iPhone 6s Plus
It is give a warning of `Embedded by dylibs/framework only run on iOS or later`  in Nimble-iOS
But my main issue is where can i see the app?
It would great if you can provide some screenshots of the app.
Thanks in advance.

**Comment by Ben-G** [comment]
@bhanuprakash0024 The current version should build successfully after you installed dependencies via Carthage. The warning you mentioned should not stop the app from running. Unfortunately I don't have a screenshot/video of the app at hand.

Let me know in case you continue to run into issues when trying to build.
