### ISSUE TITLE
"An extremely simple example app, being built with ReSwift" - not really ;-)

### ISSUE THREAD

**Issue by ColinEberhardt** [Swift-Flow/CounterExample#8]
Hi, I'm an author for Ray Wenderlich's website and am looking to write an article on ReSwift. I've had quite a lot of Redux experience (I'm more of a JS developer than an iOS developer at the moment).

I definitely like the look of ReSwift - nice job!

Although, this example is described as:

> A very simple counter app implemented with ReSwift.

And unfortunately, it is not! The addition of time travel makes your actions look really quite complicated. Which was a real turn-off when I initially looked at the code.

I think your simplest example should be just that .... really really simple.

I'd propose having nothing more than the code in the ReSwift README, just like this:

https://github.com/ColinEberhardt/CounterExample

I'd be happy to add a README, and some lightweight docs, to this above project and move it under the ReSwift org if you like?

**Comment by Ben-G** [comment]
Hey @ColinEberhardt!

> I'm an author for Ray Wenderlich's website and am looking to write an article on ReSwift.

That's awesome! I've read a lot of your tutorials before and really enjoyed them.

> And unfortunately, it is not! The addition of time travel makes your actions look really quite complicated.

Very good point, I haven't revisited this example in a while. Would be great to have your repo as part of this org. 

I'll add you as a contributor. Once it's in we can link to it from the main ReSwift repo.

Thanks a lot for bringing this up 💯

**Comment by ColinEberhardt** [comment]
Done: https://github.com/ReSwift/ReSwift/pull/141

Thanks for adding me - and if I spot anything else, I'll certainly contribute. This looks like a really good project.
