### ISSUE TITLE
CounterExample-Navigation-TimeTravel is failing to build...

### ISSUE THREAD

**Issue by frranck** [Swift-Flow/CounterExample#9]
Hi,
CounterExample-Navigation-TimeTravel is failing to build at the moment with xcode 8.1, would be great to fix it...

**Comment by crobicha** [comment]
👍  I am unable to build as well, getting a "CLEAN FAILED" error message with exit code 65 when running "carthage update" command

Screenshot: https://cl.ly/2T452t372E3S

**Comment by Ben-G** [comment]
@frranck @crobicha Thanks for making me aware. Will fix this soon! With this fairly large project it's often hard to keep up with frequent Swift updates on all example projects.

Will fix this; in the meantime you can also check out some other examples:
https://github.com/ReSwift/GitHubBrowserExample
https://github.com/ReSwift/CounterExample

**Comment by Ben-G** [comment]
@frranck @crobicha I know this is late; but fixed by #10.

This entire migration was pretty painful through having so many different projects!
